spring:
  datasource:
    driverClassName: org.h2.Driver
    password: library
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

# Actuator com.library.api
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  enable: true

# FTP config
ftp:
  username: dlpuser
  password: rNrKYTX9g7z3RgJRmxWuGHbeu
  server: sftp.dlptest.com
  port: 21
  keepAliveTimout: 10

# JWT config
lampiris:
  jwt:
    expiration: 86400000
    secret: B8A0C3AD1ADF342067FCCE82CBDA8DA564E34BA988B7300CB4ABE0EEA77C0DB4